//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace LibrarySystem {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsAdjustment : DataSet {
        
        private tblAdjustmentsDataTable tabletblAdjustments;
        
        public dsAdjustment() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsAdjustment(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblAdjustments"] != null)) {
                    this.Tables.Add(new tblAdjustmentsDataTable(ds.Tables["tblAdjustments"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblAdjustmentsDataTable tblAdjustments {
            get {
                return this.tabletblAdjustments;
            }
        }
        
        public override DataSet Clone() {
            dsAdjustment cln = ((dsAdjustment)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["tblAdjustments"] != null)) {
                this.Tables.Add(new tblAdjustmentsDataTable(ds.Tables["tblAdjustments"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletblAdjustments = ((tblAdjustmentsDataTable)(this.Tables["tblAdjustments"]));
            if ((this.tabletblAdjustments != null)) {
                this.tabletblAdjustments.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsAdjustment";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsAdjustment.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletblAdjustments = new tblAdjustmentsDataTable();
            this.Tables.Add(this.tabletblAdjustments);
        }
        
        private bool ShouldSerializetblAdjustments() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void tblAdjustmentsRowChangeEventHandler(object sender, tblAdjustmentsRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblAdjustmentsDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnBookNo;
            
            private DataColumn columnISBN;
            
            private DataColumn columnBookTitle;
            
            private DataColumn columnCategoryName;
            
            private DataColumn columnLibrarianID;
            
            private DataColumn columnFullname;
            
            private DataColumn columnDateAdjust;
            
            internal tblAdjustmentsDataTable() : 
                    base("tblAdjustments") {
                this.InitClass();
            }
            
            internal tblAdjustmentsDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn BookNoColumn {
                get {
                    return this.columnBookNo;
                }
            }
            
            internal DataColumn ISBNColumn {
                get {
                    return this.columnISBN;
                }
            }
            
            internal DataColumn BookTitleColumn {
                get {
                    return this.columnBookTitle;
                }
            }
            
            internal DataColumn CategoryNameColumn {
                get {
                    return this.columnCategoryName;
                }
            }
            
            internal DataColumn LibrarianIDColumn {
                get {
                    return this.columnLibrarianID;
                }
            }
            
            internal DataColumn FullnameColumn {
                get {
                    return this.columnFullname;
                }
            }
            
            internal DataColumn DateAdjustColumn {
                get {
                    return this.columnDateAdjust;
                }
            }
            
            public tblAdjustmentsRow this[int index] {
                get {
                    return ((tblAdjustmentsRow)(this.Rows[index]));
                }
            }
            
            public event tblAdjustmentsRowChangeEventHandler tblAdjustmentsRowChanged;
            
            public event tblAdjustmentsRowChangeEventHandler tblAdjustmentsRowChanging;
            
            public event tblAdjustmentsRowChangeEventHandler tblAdjustmentsRowDeleted;
            
            public event tblAdjustmentsRowChangeEventHandler tblAdjustmentsRowDeleting;
            
            public void AddtblAdjustmentsRow(tblAdjustmentsRow row) {
                this.Rows.Add(row);
            }
            
            public tblAdjustmentsRow AddtblAdjustmentsRow(string BookNo, string ISBN, string BookTitle, string CategoryName, string LibrarianID, string Fullname, System.DateTime DateAdjust) {
                tblAdjustmentsRow rowtblAdjustmentsRow = ((tblAdjustmentsRow)(this.NewRow()));
                rowtblAdjustmentsRow.ItemArray = new object[] {
                        BookNo,
                        ISBN,
                        BookTitle,
                        CategoryName,
                        LibrarianID,
                        Fullname,
                        DateAdjust};
                this.Rows.Add(rowtblAdjustmentsRow);
                return rowtblAdjustmentsRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tblAdjustmentsDataTable cln = ((tblAdjustmentsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tblAdjustmentsDataTable();
            }
            
            internal void InitVars() {
                this.columnBookNo = this.Columns["BookNo"];
                this.columnISBN = this.Columns["ISBN"];
                this.columnBookTitle = this.Columns["BookTitle"];
                this.columnCategoryName = this.Columns["CategoryName"];
                this.columnLibrarianID = this.Columns["LibrarianID"];
                this.columnFullname = this.Columns["Fullname"];
                this.columnDateAdjust = this.Columns["DateAdjust"];
            }
            
            private void InitClass() {
                this.columnBookNo = new DataColumn("BookNo", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBookNo);
                this.columnISBN = new DataColumn("ISBN", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnISBN);
                this.columnBookTitle = new DataColumn("BookTitle", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBookTitle);
                this.columnCategoryName = new DataColumn("CategoryName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCategoryName);
                this.columnLibrarianID = new DataColumn("LibrarianID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLibrarianID);
                this.columnFullname = new DataColumn("Fullname", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFullname);
                this.columnDateAdjust = new DataColumn("DateAdjust", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDateAdjust);
            }
            
            public tblAdjustmentsRow NewtblAdjustmentsRow() {
                return ((tblAdjustmentsRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tblAdjustmentsRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tblAdjustmentsRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblAdjustmentsRowChanged != null)) {
                    this.tblAdjustmentsRowChanged(this, new tblAdjustmentsRowChangeEvent(((tblAdjustmentsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblAdjustmentsRowChanging != null)) {
                    this.tblAdjustmentsRowChanging(this, new tblAdjustmentsRowChangeEvent(((tblAdjustmentsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblAdjustmentsRowDeleted != null)) {
                    this.tblAdjustmentsRowDeleted(this, new tblAdjustmentsRowChangeEvent(((tblAdjustmentsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblAdjustmentsRowDeleting != null)) {
                    this.tblAdjustmentsRowDeleting(this, new tblAdjustmentsRowChangeEvent(((tblAdjustmentsRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovetblAdjustmentsRow(tblAdjustmentsRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblAdjustmentsRow : DataRow {
            
            private tblAdjustmentsDataTable tabletblAdjustments;
            
            internal tblAdjustmentsRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblAdjustments = ((tblAdjustmentsDataTable)(this.Table));
            }
            
            public string BookNo {
                get {
                    try {
                        return ((string)(this[this.tabletblAdjustments.BookNoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblAdjustments.BookNoColumn] = value;
                }
            }
            
            public string ISBN {
                get {
                    try {
                        return ((string)(this[this.tabletblAdjustments.ISBNColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblAdjustments.ISBNColumn] = value;
                }
            }
            
            public string BookTitle {
                get {
                    try {
                        return ((string)(this[this.tabletblAdjustments.BookTitleColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblAdjustments.BookTitleColumn] = value;
                }
            }
            
            public string CategoryName {
                get {
                    try {
                        return ((string)(this[this.tabletblAdjustments.CategoryNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblAdjustments.CategoryNameColumn] = value;
                }
            }
            
            public string LibrarianID {
                get {
                    try {
                        return ((string)(this[this.tabletblAdjustments.LibrarianIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblAdjustments.LibrarianIDColumn] = value;
                }
            }
            
            public string Fullname {
                get {
                    try {
                        return ((string)(this[this.tabletblAdjustments.FullnameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblAdjustments.FullnameColumn] = value;
                }
            }
            
            public System.DateTime DateAdjust {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabletblAdjustments.DateAdjustColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblAdjustments.DateAdjustColumn] = value;
                }
            }
            
            public bool IsBookNoNull() {
                return this.IsNull(this.tabletblAdjustments.BookNoColumn);
            }
            
            public void SetBookNoNull() {
                this[this.tabletblAdjustments.BookNoColumn] = System.Convert.DBNull;
            }
            
            public bool IsISBNNull() {
                return this.IsNull(this.tabletblAdjustments.ISBNColumn);
            }
            
            public void SetISBNNull() {
                this[this.tabletblAdjustments.ISBNColumn] = System.Convert.DBNull;
            }
            
            public bool IsBookTitleNull() {
                return this.IsNull(this.tabletblAdjustments.BookTitleColumn);
            }
            
            public void SetBookTitleNull() {
                this[this.tabletblAdjustments.BookTitleColumn] = System.Convert.DBNull;
            }
            
            public bool IsCategoryNameNull() {
                return this.IsNull(this.tabletblAdjustments.CategoryNameColumn);
            }
            
            public void SetCategoryNameNull() {
                this[this.tabletblAdjustments.CategoryNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsLibrarianIDNull() {
                return this.IsNull(this.tabletblAdjustments.LibrarianIDColumn);
            }
            
            public void SetLibrarianIDNull() {
                this[this.tabletblAdjustments.LibrarianIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsFullnameNull() {
                return this.IsNull(this.tabletblAdjustments.FullnameColumn);
            }
            
            public void SetFullnameNull() {
                this[this.tabletblAdjustments.FullnameColumn] = System.Convert.DBNull;
            }
            
            public bool IsDateAdjustNull() {
                return this.IsNull(this.tabletblAdjustments.DateAdjustColumn);
            }
            
            public void SetDateAdjustNull() {
                this[this.tabletblAdjustments.DateAdjustColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblAdjustmentsRowChangeEvent : EventArgs {
            
            private tblAdjustmentsRow eventRow;
            
            private DataRowAction eventAction;
            
            public tblAdjustmentsRowChangeEvent(tblAdjustmentsRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tblAdjustmentsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
