//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace LibrarySystem {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsBarrowers_Fines : DataSet {
        
        private tblBarrowersDataTable tabletblBarrowers;
        
        public dsBarrowers_Fines() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsBarrowers_Fines(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblBarrowers"] != null)) {
                    this.Tables.Add(new tblBarrowersDataTable(ds.Tables["tblBarrowers"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblBarrowersDataTable tblBarrowers {
            get {
                return this.tabletblBarrowers;
            }
        }
        
        public override DataSet Clone() {
            dsBarrowers_Fines cln = ((dsBarrowers_Fines)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["tblBarrowers"] != null)) {
                this.Tables.Add(new tblBarrowersDataTable(ds.Tables["tblBarrowers"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletblBarrowers = ((tblBarrowersDataTable)(this.Tables["tblBarrowers"]));
            if ((this.tabletblBarrowers != null)) {
                this.tabletblBarrowers.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsBarrowers_Fines";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsBarrowers_Fines.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletblBarrowers = new tblBarrowersDataTable();
            this.Tables.Add(this.tabletblBarrowers);
        }
        
        private bool ShouldSerializetblBarrowers() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void tblBarrowersRowChangeEventHandler(object sender, tblBarrowersRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblBarrowersDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnBarrowerID;
            
            private DataColumn columnFullname;
            
            private DataColumn columnCourseName;
            
            private DataColumn columnLevelName;
            
            private DataColumn columnTotalFines;
            
            internal tblBarrowersDataTable() : 
                    base("tblBarrowers") {
                this.InitClass();
            }
            
            internal tblBarrowersDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn BarrowerIDColumn {
                get {
                    return this.columnBarrowerID;
                }
            }
            
            internal DataColumn FullnameColumn {
                get {
                    return this.columnFullname;
                }
            }
            
            internal DataColumn CourseNameColumn {
                get {
                    return this.columnCourseName;
                }
            }
            
            internal DataColumn LevelNameColumn {
                get {
                    return this.columnLevelName;
                }
            }
            
            internal DataColumn TotalFinesColumn {
                get {
                    return this.columnTotalFines;
                }
            }
            
            public tblBarrowersRow this[int index] {
                get {
                    return ((tblBarrowersRow)(this.Rows[index]));
                }
            }
            
            public event tblBarrowersRowChangeEventHandler tblBarrowersRowChanged;
            
            public event tblBarrowersRowChangeEventHandler tblBarrowersRowChanging;
            
            public event tblBarrowersRowChangeEventHandler tblBarrowersRowDeleted;
            
            public event tblBarrowersRowChangeEventHandler tblBarrowersRowDeleting;
            
            public void AddtblBarrowersRow(tblBarrowersRow row) {
                this.Rows.Add(row);
            }
            
            public tblBarrowersRow AddtblBarrowersRow(string BarrowerID, string Fullname, string CourseName, string LevelName, System.Double TotalFines) {
                tblBarrowersRow rowtblBarrowersRow = ((tblBarrowersRow)(this.NewRow()));
                rowtblBarrowersRow.ItemArray = new object[] {
                        BarrowerID,
                        Fullname,
                        CourseName,
                        LevelName,
                        TotalFines};
                this.Rows.Add(rowtblBarrowersRow);
                return rowtblBarrowersRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tblBarrowersDataTable cln = ((tblBarrowersDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tblBarrowersDataTable();
            }
            
            internal void InitVars() {
                this.columnBarrowerID = this.Columns["BarrowerID"];
                this.columnFullname = this.Columns["Fullname"];
                this.columnCourseName = this.Columns["CourseName"];
                this.columnLevelName = this.Columns["LevelName"];
                this.columnTotalFines = this.Columns["TotalFines"];
            }
            
            private void InitClass() {
                this.columnBarrowerID = new DataColumn("BarrowerID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBarrowerID);
                this.columnFullname = new DataColumn("Fullname", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFullname);
                this.columnCourseName = new DataColumn("CourseName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCourseName);
                this.columnLevelName = new DataColumn("LevelName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLevelName);
                this.columnTotalFines = new DataColumn("TotalFines", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTotalFines);
            }
            
            public tblBarrowersRow NewtblBarrowersRow() {
                return ((tblBarrowersRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tblBarrowersRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tblBarrowersRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblBarrowersRowChanged != null)) {
                    this.tblBarrowersRowChanged(this, new tblBarrowersRowChangeEvent(((tblBarrowersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblBarrowersRowChanging != null)) {
                    this.tblBarrowersRowChanging(this, new tblBarrowersRowChangeEvent(((tblBarrowersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblBarrowersRowDeleted != null)) {
                    this.tblBarrowersRowDeleted(this, new tblBarrowersRowChangeEvent(((tblBarrowersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblBarrowersRowDeleting != null)) {
                    this.tblBarrowersRowDeleting(this, new tblBarrowersRowChangeEvent(((tblBarrowersRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovetblBarrowersRow(tblBarrowersRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblBarrowersRow : DataRow {
            
            private tblBarrowersDataTable tabletblBarrowers;
            
            internal tblBarrowersRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblBarrowers = ((tblBarrowersDataTable)(this.Table));
            }
            
            public string BarrowerID {
                get {
                    try {
                        return ((string)(this[this.tabletblBarrowers.BarrowerIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBarrowers.BarrowerIDColumn] = value;
                }
            }
            
            public string Fullname {
                get {
                    try {
                        return ((string)(this[this.tabletblBarrowers.FullnameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBarrowers.FullnameColumn] = value;
                }
            }
            
            public string CourseName {
                get {
                    try {
                        return ((string)(this[this.tabletblBarrowers.CourseNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBarrowers.CourseNameColumn] = value;
                }
            }
            
            public string LevelName {
                get {
                    try {
                        return ((string)(this[this.tabletblBarrowers.LevelNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBarrowers.LevelNameColumn] = value;
                }
            }
            
            public System.Double TotalFines {
                get {
                    try {
                        return ((System.Double)(this[this.tabletblBarrowers.TotalFinesColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBarrowers.TotalFinesColumn] = value;
                }
            }
            
            public bool IsBarrowerIDNull() {
                return this.IsNull(this.tabletblBarrowers.BarrowerIDColumn);
            }
            
            public void SetBarrowerIDNull() {
                this[this.tabletblBarrowers.BarrowerIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsFullnameNull() {
                return this.IsNull(this.tabletblBarrowers.FullnameColumn);
            }
            
            public void SetFullnameNull() {
                this[this.tabletblBarrowers.FullnameColumn] = System.Convert.DBNull;
            }
            
            public bool IsCourseNameNull() {
                return this.IsNull(this.tabletblBarrowers.CourseNameColumn);
            }
            
            public void SetCourseNameNull() {
                this[this.tabletblBarrowers.CourseNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsLevelNameNull() {
                return this.IsNull(this.tabletblBarrowers.LevelNameColumn);
            }
            
            public void SetLevelNameNull() {
                this[this.tabletblBarrowers.LevelNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsTotalFinesNull() {
                return this.IsNull(this.tabletblBarrowers.TotalFinesColumn);
            }
            
            public void SetTotalFinesNull() {
                this[this.tabletblBarrowers.TotalFinesColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblBarrowersRowChangeEvent : EventArgs {
            
            private tblBarrowersRow eventRow;
            
            private DataRowAction eventAction;
            
            public tblBarrowersRowChangeEvent(tblBarrowersRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tblBarrowersRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
