//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace LibrarySystem {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsBooks : DataSet {
        
        private tblBooksDataTable tabletblBooks;
        
        public dsBooks() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsBooks(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblBooks"] != null)) {
                    this.Tables.Add(new tblBooksDataTable(ds.Tables["tblBooks"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblBooksDataTable tblBooks {
            get {
                return this.tabletblBooks;
            }
        }
        
        public override DataSet Clone() {
            dsBooks cln = ((dsBooks)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["tblBooks"] != null)) {
                this.Tables.Add(new tblBooksDataTable(ds.Tables["tblBooks"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletblBooks = ((tblBooksDataTable)(this.Tables["tblBooks"]));
            if ((this.tabletblBooks != null)) {
                this.tabletblBooks.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsBooks";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsBooks.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletblBooks = new tblBooksDataTable();
            this.Tables.Add(this.tabletblBooks);
        }
        
        private bool ShouldSerializetblBooks() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void tblBooksRowChangeEventHandler(object sender, tblBooksRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblBooksDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnCategoryName;
            
            private DataColumn columnBookNo;
            
            private DataColumn columnISBN;
            
            private DataColumn columnBookTitle;
            
            private DataColumn columnQty;
            
            private DataColumn columnBarrowed;
            
            private DataColumn columnAvailable;
            
            internal tblBooksDataTable() : 
                    base("tblBooks") {
                this.InitClass();
            }
            
            internal tblBooksDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn CategoryNameColumn {
                get {
                    return this.columnCategoryName;
                }
            }
            
            internal DataColumn BookNoColumn {
                get {
                    return this.columnBookNo;
                }
            }
            
            internal DataColumn ISBNColumn {
                get {
                    return this.columnISBN;
                }
            }
            
            internal DataColumn BookTitleColumn {
                get {
                    return this.columnBookTitle;
                }
            }
            
            internal DataColumn QtyColumn {
                get {
                    return this.columnQty;
                }
            }
            
            internal DataColumn BarrowedColumn {
                get {
                    return this.columnBarrowed;
                }
            }
            
            internal DataColumn AvailableColumn {
                get {
                    return this.columnAvailable;
                }
            }
            
            public tblBooksRow this[int index] {
                get {
                    return ((tblBooksRow)(this.Rows[index]));
                }
            }
            
            public event tblBooksRowChangeEventHandler tblBooksRowChanged;
            
            public event tblBooksRowChangeEventHandler tblBooksRowChanging;
            
            public event tblBooksRowChangeEventHandler tblBooksRowDeleted;
            
            public event tblBooksRowChangeEventHandler tblBooksRowDeleting;
            
            public void AddtblBooksRow(tblBooksRow row) {
                this.Rows.Add(row);
            }
            
            public tblBooksRow AddtblBooksRow(string CategoryName, string BookNo, string ISBN, string BookTitle, System.Double Qty, System.Double Barrowed, System.Double Available) {
                tblBooksRow rowtblBooksRow = ((tblBooksRow)(this.NewRow()));
                rowtblBooksRow.ItemArray = new object[] {
                        CategoryName,
                        BookNo,
                        ISBN,
                        BookTitle,
                        Qty,
                        Barrowed,
                        Available};
                this.Rows.Add(rowtblBooksRow);
                return rowtblBooksRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tblBooksDataTable cln = ((tblBooksDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tblBooksDataTable();
            }
            
            internal void InitVars() {
                this.columnCategoryName = this.Columns["CategoryName"];
                this.columnBookNo = this.Columns["BookNo"];
                this.columnISBN = this.Columns["ISBN"];
                this.columnBookTitle = this.Columns["BookTitle"];
                this.columnQty = this.Columns["Qty"];
                this.columnBarrowed = this.Columns["Barrowed"];
                this.columnAvailable = this.Columns["Available"];
            }
            
            private void InitClass() {
                this.columnCategoryName = new DataColumn("CategoryName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCategoryName);
                this.columnBookNo = new DataColumn("BookNo", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBookNo);
                this.columnISBN = new DataColumn("ISBN", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnISBN);
                this.columnBookTitle = new DataColumn("BookTitle", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBookTitle);
                this.columnQty = new DataColumn("Qty", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnQty);
                this.columnBarrowed = new DataColumn("Barrowed", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBarrowed);
                this.columnAvailable = new DataColumn("Available", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAvailable);
            }
            
            public tblBooksRow NewtblBooksRow() {
                return ((tblBooksRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tblBooksRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tblBooksRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblBooksRowChanged != null)) {
                    this.tblBooksRowChanged(this, new tblBooksRowChangeEvent(((tblBooksRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblBooksRowChanging != null)) {
                    this.tblBooksRowChanging(this, new tblBooksRowChangeEvent(((tblBooksRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblBooksRowDeleted != null)) {
                    this.tblBooksRowDeleted(this, new tblBooksRowChangeEvent(((tblBooksRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblBooksRowDeleting != null)) {
                    this.tblBooksRowDeleting(this, new tblBooksRowChangeEvent(((tblBooksRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovetblBooksRow(tblBooksRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblBooksRow : DataRow {
            
            private tblBooksDataTable tabletblBooks;
            
            internal tblBooksRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblBooks = ((tblBooksDataTable)(this.Table));
            }
            
            public string CategoryName {
                get {
                    try {
                        return ((string)(this[this.tabletblBooks.CategoryNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBooks.CategoryNameColumn] = value;
                }
            }
            
            public string BookNo {
                get {
                    try {
                        return ((string)(this[this.tabletblBooks.BookNoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBooks.BookNoColumn] = value;
                }
            }
            
            public string ISBN {
                get {
                    try {
                        return ((string)(this[this.tabletblBooks.ISBNColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBooks.ISBNColumn] = value;
                }
            }
            
            public string BookTitle {
                get {
                    try {
                        return ((string)(this[this.tabletblBooks.BookTitleColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBooks.BookTitleColumn] = value;
                }
            }
            
            public System.Double Qty {
                get {
                    try {
                        return ((System.Double)(this[this.tabletblBooks.QtyColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBooks.QtyColumn] = value;
                }
            }
            
            public System.Double Barrowed {
                get {
                    try {
                        return ((System.Double)(this[this.tabletblBooks.BarrowedColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBooks.BarrowedColumn] = value;
                }
            }
            
            public System.Double Available {
                get {
                    try {
                        return ((System.Double)(this[this.tabletblBooks.AvailableColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblBooks.AvailableColumn] = value;
                }
            }
            
            public bool IsCategoryNameNull() {
                return this.IsNull(this.tabletblBooks.CategoryNameColumn);
            }
            
            public void SetCategoryNameNull() {
                this[this.tabletblBooks.CategoryNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsBookNoNull() {
                return this.IsNull(this.tabletblBooks.BookNoColumn);
            }
            
            public void SetBookNoNull() {
                this[this.tabletblBooks.BookNoColumn] = System.Convert.DBNull;
            }
            
            public bool IsISBNNull() {
                return this.IsNull(this.tabletblBooks.ISBNColumn);
            }
            
            public void SetISBNNull() {
                this[this.tabletblBooks.ISBNColumn] = System.Convert.DBNull;
            }
            
            public bool IsBookTitleNull() {
                return this.IsNull(this.tabletblBooks.BookTitleColumn);
            }
            
            public void SetBookTitleNull() {
                this[this.tabletblBooks.BookTitleColumn] = System.Convert.DBNull;
            }
            
            public bool IsQtyNull() {
                return this.IsNull(this.tabletblBooks.QtyColumn);
            }
            
            public void SetQtyNull() {
                this[this.tabletblBooks.QtyColumn] = System.Convert.DBNull;
            }
            
            public bool IsBarrowedNull() {
                return this.IsNull(this.tabletblBooks.BarrowedColumn);
            }
            
            public void SetBarrowedNull() {
                this[this.tabletblBooks.BarrowedColumn] = System.Convert.DBNull;
            }
            
            public bool IsAvailableNull() {
                return this.IsNull(this.tabletblBooks.AvailableColumn);
            }
            
            public void SetAvailableNull() {
                this[this.tabletblBooks.AvailableColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblBooksRowChangeEvent : EventArgs {
            
            private tblBooksRow eventRow;
            
            private DataRowAction eventAction;
            
            public tblBooksRowChangeEvent(tblBooksRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tblBooksRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
